//  these variables are used within the modules
DIMENSION_CENTER = 0;
DIMENSION_LEFT = 1;
DIMENSION_RIGHT = 2;
DIMENSION_OUTSIDE = 3;
DIMENSION_ABOVE = 4;
DIMENSION_UNDER = 5;

RENDER_MODE_3D = "3D";
RENDER_MODE_FLAT = "Flat";
